name = "PhysiologyPlotting"
uuid = "d5a2a81f-3167-4eb5-8f67-b1ebe6a4430d"
authors = ["Matthew Tarchick"]
version = "0.0.1"

[deps]
ElectroPhysiology = "da7a9670-f599-43ac-b818-143f8bf87d45"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
ElectroPhysiology = "0.3"
Plots = "1"
julia = "1"
PyPlot = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
